
import { Inter } from 'next/font/google';
import Navbar from './coordinates/Navbar';
import './global.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'UK Police Stats',
  description: 'Generated by create next app',
  name: 'viewport',
  content: "width=device-width, initial-scale=1, user-scalable=no",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Navbar />
      {children}
      </body>
    </html>
  )
}
