
import { Inter } from 'next/font/google';
import Navbar from './coordinates/Navbar';
import './global.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'UK Police Stats',
  description: 'Generated by create next app',
  name: 'viewport',
  content: "width=device-width, initial-scale=1, user-scalable=no",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <link rel="preconnect" href="https://fonts.googleapis.com"/>
      <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin/>
      <link href="https://fonts.googleapis.com/css2?family=Lobster+Two&family=Roboto&display=swap" rel="stylesheet"/>
      <Navbar />
      {children}
      </body>
    </html>
  )
}
